version: "3.8"

networks:
  default:

services:
  backend:
    container_name: backend
    # depends_on:
    #   - mysql-db
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - 3333:3333
    stdin_open: true
    tty: true
    networks:
      - default

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    # env_file: ./frontend/.env
    ports:
      - 80:80
    stdin_open: true
    tty: true
    networks:
      - default
